<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'index'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">Index</a>
        <a href="<?php echo $this->url(
            array('controller'=>'user'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">User</a>
        <a href="<?php echo $this->url(
            array('controller'=>'pet'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">Pet</a>
        <a href="<?php echo $this->url(
            array('controller'=>'language'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">Language</a>
        <a href="<?php echo $this->url(
            array('controller'=>'album'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">Album</a>
        <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',						// 'default' ES EL MODULO POR DEFECTO
            true) ?>">Guestbook</a>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
