<?php 
$this->title = "Users";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'user',
        'action'=>'add'));?>">Add new user</a></p>
<table>
<tr>
    <th>Name</th>
    <th>E-mail</th>
    <th>Password</th>
    <th>Description</th>
    <th>Photo</th>
    <th>Coders</th>
    <th>City</th>
    <th>Role</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>
    <td><?php echo $this->escape($user->name);?></td>
    <td><?php echo $this->escape($user->email);?></td>
    <td><?php echo $this->escape($user->password);?></td>
    <td><?php echo $this->escape($user->description);?></td>
    <td><?php echo $this->escape($user->photo);?></td>
    <td><?php echo $this->escape($user->coders);?></td>
    <td><?php echo $this->escape($user->cities_idcity);?></td>
    <td><?php echo $this->escape($user->roles_idrole);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'edit', 'iduser'=>$user->iduser));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'delete', 'iduser'=>$user->iduser));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>